apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgp-app
  namespace: argocd
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/pedrohro1992/gitops-cookbook-sc.git
    path: ch07/manifests/bgd
    targetRevision: main
  syncPolicy:
    automated: {}
