apiVersion: v1
#Create secret to enable communication between argocd and git servers
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository #Set the secret type as repository
stringData:
  type: git
  url: https://github.com/argoproj/private-repo
  password: pass
  username: use
