apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository #Name of the Repository
stringData:
  type: git
  repo: git@github.com:argoproj/my-private-repository
  githubAppID: 1 # Sets GitHub App pramaeters
  githubAppInstallationID: 2
  githubAppEnterpriseBaseUrl: https://ghe.example.com/api/v3 # Only valid if GitHub App Enterprise is used
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -- PUT SSH KEY HERE -- 
    -----END OPENSSH PRIVATE KEY-----
