apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml

configMapGenerator:
  - name: pacman-configmap
    files:
      - ./dev-literals/connection.propeties
