apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./deployment.yaml
- ./service.yaml

images:
- name: lordofthejars/pacman-kikd
  newTag: 1.0.2


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
patches:
  - target:
      group: apps 
      version: v1
      kind: Deployment
      name: pacman-kikd
      namespace: pacman
    path: external_path.yaml 
