apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: stage
images:
  - name: lordofthejars/pacman-kikd
    newTag: 1.2.0-beta

namePrefix: staging-
nameSuffix: -v1-2-0
