image:
  repository: quay.io/gitops-cookbook/music
  tag: "1.0.0"
  pullPolicy: Always
  containerPort: 8080
  replicaCount: 1

# postgresql:
#   server: jdbc:postgresql://music-db-postgresql:5432/mydb
#   postgresqlUsername: my-default
#   secretName: music-db-postgresql
#   secretKey: postgres-password
#   postgresqlPassword: postgres

postgresql:
  server: jdbc:postgresql://music-db-postgresql:5432/mydb
  auth:
    enablePostgresUser: true
    postgresPassword: "StrongPassword"
    username: "app1"
    password: "AppPassword"
    database: "mydb"
  # primary:
  #   persistence:
  #     enabled: true
  #     existingClaim: "postgresql-data-claim"
