apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gitops-cookbook/gitops-cookbook-sc.git
        revision: main
        directories:
          - path: ch08/bgd-gen/*
  template: #
    metadata:
      name: "{{path[0]}}{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/gitops-cookbook/gitops-cookbook-sc.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
