apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gitops-cookbook/gitops-cookbook-sc.git
        revision: main
        directores:
          - path: ch08/bgd-gen/*
  template: #
    metadata:
      name: "{{path[0]}}{{path[2]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/gitops-cookbook/gitops-cookbook-sc.git
        targetRevision: main
        path: ch08/bgd-gen/{{cluster}}
      destination:
        server: "{{url}}" #
        namespace: "{{location}}"
